service: hello-world-alexa-skill

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'} # default stage is dev, but you can override it.
  region: us-east-1 # Alexa is only available in eu-west-1 or us-east-1
  memorySize: 256
  cfLogs: true # AWS Cloudformation logging

functions:
  skill:
    handler: src/index.handler # path to the alexa handler - {path}/{filename}.{handler function}
    description: Example hello world Alexa skill
    events:
      - alexaSkill: amzn1.ask.skill.27475f49-2d2b-445d-9bee-5cd79fa0a08a

plugins:
  - serverless-webpack
  - serverless-plugin-webpack-permission
custom:
  webpack:
    includeModules: true # Node modules configuration for packaging
